# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autohost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autohostname', models.CharField(default=0, max_length=100, verbose_name='\u4e3b\u673a\u540d')),
                ('autoip', models.GenericIPAddressField(default=0, verbose_name='IP')),
                ('autodisk', models.CharField(default=0, max_length=100, verbose_name='\u786c\u76d8')),
                ('autocpucore', models.CharField(default=0, max_length=100, verbose_name='cpu\u4f7f\u7528\u7387')),
                ('autoTime', models.DateTimeField(auto_now_add=True, verbose_name='\u4e0a\u62a5\u65f6\u95f4')),
                ('mencached', models.CharField(default=0, max_length=100, verbose_name='\u9875\u9762\u7f13\u5b58')),
                ('menbuffer', models.CharField(default=0, max_length=100, verbose_name='\u9ad8\u901f\u7f13\u5b58')),
                ('menswap', models.CharField(default=0, max_length=100, verbose_name='\u4ea4\u6362\u5206\u533a')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default='server', help_text='\u683c\u5f0f\u4e3aserver+\u5e73\u53f0+\u7f16\u53f7', max_length=50, unique=True, verbose_name='\u4e3b\u673a\u540d\u79f0')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='\u4e3b\u673aIP')),
                ('osversion', models.CharField(default='Linux', max_length=50, verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
                ('memory', models.CharField(default='2G', max_length=50, verbose_name='\u5185\u5b58')),
                ('disk', models.CharField(max_length=50, verbose_name='\u786c\u76d8')),
                ('model_name', models.CharField(blank=True, max_length=50, verbose_name='\u578b\u53f7')),
                ('cpu_core', models.CharField(max_length=50, verbose_name='cpu\u6838\u6570')),
                ('host_status', models.IntegerField(choices=[(1, '\u5728\u7528'), (2, '\u7a7a\u95f2'), (3, '\u505c\u7528')], default=1, verbose_name='\u4e3b\u673a\u72b6\u6001')),
                ('test', models.CharField(max_length=50, verbose_name='test')),
            ],
            options={
                'verbose_name': '\u4e3b\u673a',
                'verbose_name_plural': '\u4e3b\u673a\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idc_name', models.CharField(max_length=100, verbose_name='\u673a\u623f')),
                ('idc_laber', models.CharField(max_length=100, verbose_name='\u6807\u7b7e')),
            ],
            options={
                'verbose_name': '\u673a\u623f',
                'verbose_name_plural': 'IDC',
            },
        ),
        migrations.CreateModel(
            name='runmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='\u6807\u7b7e')),
                ('modelname', models.CharField(max_length=100, verbose_name='\u6a21\u5757\u540d')),
            ],
            options={
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6a21\u5757\u540d',
            },
        ),
        migrations.CreateModel(
            name='uploadfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filetitle', models.CharField(default=0, max_length=255, verbose_name='\u6587\u4ef6\u540d')),
                ('filepath', models.FilePathField(default=0, max_length=255, verbose_name='\u6587\u4ef6\u76ee\u5f55')),
                ('fileexit', models.BooleanField(default=True, verbose_name='\u662f\u5426\u5b58\u5728')),
                ('uploadtime', models.DateTimeField(auto_now_add=True, verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
                ('filesize', models.CharField(default=0, max_length=255, verbose_name='\u6587\u4ef6\u5927\u5c0f')),
            ],
            options={
                'verbose_name': '\u6587\u4ef6\u540d',
                'verbose_name_plural': '\u4e0a\u4f20\u6587\u4ef6',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='host_IDC',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='suyu.IDC'),
        ),
    ]
