# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-20 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suyu', '0004_auto_20171030_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='filepath',
            field=models.CharField(default=2, max_length=255, verbose_name='\u6587\u4ef6\u76ee\u5f55'),
        ),
    ]
