# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suyu', '0006_runmodel_modelid'),
    ]

    operations = [
        migrations.CreateModel(
            name='redisinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostip', models.GenericIPAddressField(default='0.0.0.0')),
                ('role', models.CharField(max_length=255)),
                ('alive', models.BooleanField(default=False)),
                ('connected', models.CharField(default=0, max_length=255)),
            ],
        ),
    ]
