# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 11:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suyu', '0007_redisinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='redisinfo',
            name='autoTime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u4e0a\u62a5\u65f6\u95f4'),
        ),
    ]
