# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaltServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=100, verbose_name='URL\u5730\u5740')),
                ('username', models.CharField(max_length=50, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=50, verbose_name='\u5bc6\u7801')),
                ('role', models.CharField(choices=[('Master', 'Master'), ('Backend', 'Backend')], default='Master', max_length=20, verbose_name='\u89d2\u8272')),
            ],
            options={
                'verbose_name': 'Salt\u670d\u52a1\u5668',
                'verbose_name_plural': 'Salt\u670d\u52a1\u5668\u5217\u8868',
                'permissions': (('salt_index_view', 'Can view Salt\u670d\u52a1\u5668'),),
            },
        ),
    ]
