# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saltstack', '0002_minions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minion_status', models.CharField(max_length=20, verbose_name='\u5728\u7ebf\u72b6\u6001')),
                ('alive_time_last', models.DateTimeField(auto_now=True, null=True)),
                ('alive_time_now', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='minions',
            name='saltserver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saltstack.saltserver', verbose_name='\u6240\u5c5eSalt\u670d\u52a1\u5668'),
        ),
        migrations.AddField(
            model_name='minionstatus',
            name='minion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saltstack.Minions'),
        ),
    ]
