# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saltstack', '0003_auto_20171130_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmdRunLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('target', models.CharField(max_length=500)),
                ('cmd', models.CharField(max_length=500)),
                ('total', models.IntegerField()),
                ('runsuccess', models.IntegerField(default=0)),
                ('runerror', models.IntegerField(default=0)),
                ('runresult', models.TextField(blank=True, max_length=65535, null=True)),
            ],
            options={
                'verbose_name': '\u547d\u4ee4\u6267\u884c\u65e5\u5fd7',
                'verbose_name_plural': '\u547d\u4ee4\u6267\u884c\u65e5\u5fd7',
            },
        ),
        migrations.CreateModel(
            name='MinionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(default='default', max_length=50, verbose_name='Minion\u7ec4')),
            ],
            options={
                'verbose_name': 'Minion\u7ec4',
                'verbose_name_plural': 'Minion\u7ec4',
            },
        ),
        migrations.CreateModel(
            name='ModuleDeployLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('target', models.CharField(max_length=100)),
                ('application', models.CharField(max_length=100)),
                ('success_hosts', models.CharField(max_length=500)),
                ('failed_hosts', models.CharField(max_length=500)),
                ('total', models.IntegerField()),
                ('log', models.TextField()),
                ('duration', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': '\u8f6f\u4ef6\u90e8\u7f72',
                'verbose_name_plural': '\u8f6f\u4ef6\u90e8\u7f72',
            },
        ),
        migrations.CreateModel(
            name='SaltJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.CharField(max_length=50, unique=True)),
                ('args', models.CharField(blank=True, max_length=50, null=True)),
                ('function', models.CharField(max_length=50)),
                ('startTime', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=500)),
                ('user', models.CharField(max_length=50)),
                ('saltserver', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Jobs\u5217\u8868',
                'verbose_name_plural': 'Jobs\u5217\u8868',
            },
        ),
        migrations.AlterField(
            model_name='minions',
            name='saltserver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saltstack.saltserver', verbose_name='\u6240\u5c5eSalt\u670d\u52a1\u5668'),
        ),
        migrations.AddField(
            model_name='miniongroup',
            name='minions',
            field=models.ManyToManyField(blank=True, to='saltstack.Minions', verbose_name='Minions'),
        ),
    ]
