# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-18 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suyusys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hefuinfo',
            old_name='heufid',
            new_name='hefuid',
        ),
    ]
