# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suyusys', '0002_auto_20171218_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='hefuinfo',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0', verbose_name='\u4e3b\u670dip'),
        ),
    ]
