# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suyusys', '0003_auto_20171205_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbserversredis',
            name='alive',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5728\u7ebf'),
        ),
        migrations.AlterField(
            model_name='dbserversredis',
            name='role',
            field=models.CharField(choices=[('master', 'master'), ('slave', 'slave')], default='slave', max_length=30, verbose_name='\u89d2\u8272'),
        ),
    ]
