# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suyusys', '0003_hefuinfo_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hefuinfo',
            name='success',
            field=models.IntegerField(default=0, verbose_name='\u662f\u5426\u5b8c\u6210'),
        ),
    ]
