# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suyusys', '0004_auto_20171219_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='hefuinfo',
            name='main_server_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
