# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suyusys', '0004_auto_20171205_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redisinfotest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostip', models.GenericIPAddressField(default='0.0.0.0')),
                ('role', models.CharField(max_length=255)),
                ('alive', models.BooleanField(default=False)),
                ('connected', models.CharField(default=0, max_length=255)),
                ('autoTime', models.DateTimeField(auto_now_add=True, verbose_name='\u4e0a\u62a5\u65f6\u95f4')),
            ],
        ),
    ]
